//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppl_DB_L25_All_CRUD_DD_03082023_Master
{


    public partial class StudentForm
    {
    }
}
